// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260315084047_AddVehicleParkingStatus")]
    partial class AddVehicleParkingStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.AccessLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int?>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("CapturedFaceImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CapturedFaceImageURL");

                    b.Property<string>("CapturedLicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EntryLogId")
                        .HasColumnType("int");

                    b.Property<int?>("ExceptionReasonId")
                        .HasColumnType("int");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsBypass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__Access_L__5E548648F597543A");

                    b.HasIndex("CameraId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EntryLogId");

                    b.HasIndex("ExceptionReasonId");

                    b.HasIndex("GateId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Access_Log");
                });

            modelBuilder.Entity("API.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Staff");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Quản trị viên",
                            IsActive = true,
                            PasswordHash = "$2a$11$3u1MjpEbkPc4kdZGmYUAWe48S2shbpWxLZIPga5ildrJXKeqOXtGG",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("API.Models.Camera", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraId"));

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CameraType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.HasKey("CameraId")
                        .HasName("PK__Camera__F971E0C89B981B26");

                    b.HasIndex("GateId");

                    b.ToTable("Camera");
                });

            modelBuilder.Entity("API.Models.CameraPlate", b =>
                {
                    b.Property<string>("CameraIP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X1")
                        .HasColumnType("int");

                    b.Property<int>("X2")
                        .HasColumnType("int");

                    b.Property<int>("Y1")
                        .HasColumnType("int");

                    b.Property<int>("Y2")
                        .HasColumnType("int");

                    b.HasKey("CameraIP");

                    b.ToTable("CameraPlates");
                });

            modelBuilder.Entity("API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BED22FBEE13");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FaceImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("FaceImageURL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F1101CCCAF2");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("API.Models.EmployeeFaceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ModelFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeFaceModels");
                });

            modelBuilder.Entity("API.Models.EmployeeFaceVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeFaceVideos");
                });

            modelBuilder.Entity("API.Models.ExceptionReason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ReasonId")
                        .HasName("PK__Exceptio__A4F8C0E71D19C4D0");

                    b.HasIndex(new[] { "ReasonCode" }, "UQ__Exceptio__A6278DA348D14177")
                        .IsUnique();

                    b.ToTable("Exception_Reason");
                });

            modelBuilder.Entity("API.Models.Gate", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GateId"));

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GateId")
                        .HasName("PK__Gate__9582C65020BEEB76");

                    b.ToTable("Gate");
                });

            modelBuilder.Entity("API.Models.GuestProfile", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("DefaultLicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FaceImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("FaceImageURL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GuestId")
                        .HasName("PK__GuestPro__0C423C12B547B8BB");

                    b.ToTable("GuestProfile");
                });

            modelBuilder.Entity("API.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PositionId")
                        .HasName("PK__Position__60BB9A79F338CF82");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("API.Models.PreRegistration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ExpectedLicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ExpectedTimeIn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ExpectedTimeOut")
                        .HasColumnType("datetime");

                    b.Property<int?>("GuestId")
                        .HasColumnType("int");

                    b.Property<int?>("HostEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVisitors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING");

                    b.HasKey("RegistrationId")
                        .HasName("PK__Pre_Regi__6EF58810D0B7AD86");

                    b.HasIndex("GuestId");

                    b.HasIndex("HostEmployeeId");

                    b.ToTable("Pre_Registration");
                });

            modelBuilder.Entity("API.Models.RegistrationLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<int>("HostEmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("LinkId");

                    b.HasIndex("HostEmployeeId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Registration_Links");
                });

            modelBuilder.Entity("API.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ParkingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("OUT");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicle__476B54920FBE48B7");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex(new[] { "LicensePlate" }, "UQ__Vehicle__026BC15CB8D416A0")
                        .IsUnique();

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("API.Models.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleTypeId")
                        .HasName("PK__VehicleT__9F449643A4120859");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("API.Models.VisitorDetail", b =>
                {
                    b.Property<int>("VisitorDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorDetailId"));

                    b.Property<string>("ExpectedFaceImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdCardNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("VisitorDetailId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Visitor_Details");
                });

            modelBuilder.Entity("API.Models.AccessLog", b =>
                {
                    b.HasOne("API.Models.Camera", "Camera")
                        .WithMany("AccessLogs")
                        .HasForeignKey("CameraId")
                        .HasConstraintName("FK_AccessLog_Camera");

                    b.HasOne("API.Models.Employee", "Employee")
                        .WithMany("AccessLogs")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_AccessLog_Employee");

                    b.HasOne("API.Models.AccessLog", "EntryLog")
                        .WithMany("InverseEntryLog")
                        .HasForeignKey("EntryLogId")
                        .HasConstraintName("FK_AccessLog_EntryLog");

                    b.HasOne("API.Models.ExceptionReason", "ExceptionReason")
                        .WithMany("AccessLogs")
                        .HasForeignKey("ExceptionReasonId")
                        .HasConstraintName("FK_AccessLog_ExceptionReason");

                    b.HasOne("API.Models.Gate", "Gate")
                        .WithMany("AccessLogs")
                        .HasForeignKey("GateId")
                        .HasConstraintName("FK_AccessLog_Gate");

                    b.HasOne("API.Models.PreRegistration", "Registration")
                        .WithMany("AccessLogs")
                        .HasForeignKey("RegistrationId")
                        .HasConstraintName("FK_AccessLog_PreRegistration");

                    b.Navigation("Camera");

                    b.Navigation("Employee");

                    b.Navigation("EntryLog");

                    b.Navigation("ExceptionReason");

                    b.Navigation("Gate");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("API.Models.AppUser", b =>
                {
                    b.HasOne("API.Models.Employee", "Employee")
                        .WithOne("AppUser")
                        .HasForeignKey("API.Models.AppUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AppUser_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API.Models.Camera", b =>
                {
                    b.HasOne("API.Models.Gate", "Gate")
                        .WithMany("Cameras")
                        .HasForeignKey("GateId")
                        .HasConstraintName("FK_Camera_Gate");

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.HasOne("API.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Employee_Department");

                    b.HasOne("API.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("FK_Employee_Position");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("API.Models.EmployeeFaceModel", b =>
                {
                    b.HasOne("API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeFaceModel_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API.Models.EmployeeFaceVideo", b =>
                {
                    b.HasOne("API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeFaceVideo_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API.Models.PreRegistration", b =>
                {
                    b.HasOne("API.Models.GuestProfile", "Guest")
                        .WithMany("PreRegistrations")
                        .HasForeignKey("GuestId")
                        .HasConstraintName("FK_PreReg_Guest");

                    b.HasOne("API.Models.Employee", "HostEmployee")
                        .WithMany("PreRegistrations")
                        .HasForeignKey("HostEmployeeId")
                        .HasConstraintName("FK_PreReg_Employee");

                    b.Navigation("Guest");

                    b.Navigation("HostEmployee");
                });

            modelBuilder.Entity("API.Models.RegistrationLink", b =>
                {
                    b.HasOne("API.Models.Employee", "HostEmployee")
                        .WithMany()
                        .HasForeignKey("HostEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RegistrationLink_Employee");

                    b.Navigation("HostEmployee");
                });

            modelBuilder.Entity("API.Models.Vehicle", b =>
                {
                    b.HasOne("API.Models.Employee", "Employee")
                        .WithMany("Vehicles")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Vehicle_Employee");

                    b.HasOne("API.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .HasConstraintName("FK_Vehicle_Type");

                    b.Navigation("Employee");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("API.Models.VisitorDetail", b =>
                {
                    b.HasOne("API.Models.PreRegistration", "Registration")
                        .WithMany("VisitorDetails")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VisitorDetail_PreRegistration");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("API.Models.AccessLog", b =>
                {
                    b.Navigation("InverseEntryLog");
                });

            modelBuilder.Entity("API.Models.Camera", b =>
                {
                    b.Navigation("AccessLogs");
                });

            modelBuilder.Entity("API.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("AppUser");

                    b.Navigation("PreRegistrations");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("API.Models.ExceptionReason", b =>
                {
                    b.Navigation("AccessLogs");
                });

            modelBuilder.Entity("API.Models.Gate", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("Cameras");
                });

            modelBuilder.Entity("API.Models.GuestProfile", b =>
                {
                    b.Navigation("PreRegistrations");
                });

            modelBuilder.Entity("API.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("API.Models.PreRegistration", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("VisitorDetails");
                });

            modelBuilder.Entity("API.Models.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
