<template>
  <div class="page-container access-page">
    <PageHeader title="Lịch sử ra vào" description="Tra cứu sự kiện kiểm soát, bằng chứng camera và các lượt ngoại lệ trên toàn hệ thống." :breadcrumbs="[{label:'Kiểm soát ra vào'},{label:'Lịch sử'}]">
      <template #actions><BaseButton variant="secondary" @click="showExportModal=true">Xuất dữ liệu</BaseButton><BaseButton variant="secondary" :loading="isLoading" @click="refreshPage">Làm mới</BaseButton></template>
    </PageHeader>

    <section class="summary-grid" aria-label="Tổng quan ra vào hôm nay">
      <BaseCard variant="kpi"><span>Tổng lượt hôm nay</span><strong>{{ summary.totalToday }}</strong><small>{{ summary.entriesToday }} vào · {{ summary.exitsToday }} ra</small></BaseCard>
      <BaseCard variant="kpi"><span>Bypass thủ công</span><strong>{{ summary.bypassToday }}</strong><small>Cần rà soát theo quy trình</small></BaseCard>
      <BaseCard variant="kpi"><span>Xe trong khu vực</span><strong>{{ summary.vehiclesInside }}</strong><small>Trạng thái đỗ xe hiện tại</small></BaseCard>
      <BaseCard variant="kpi"><span>Tỷ lệ thành công</span><strong>{{ summary.successRate }}%</strong><small>{{ summary.exceptionsToday }} ngoại lệ hôm nay</small></BaseCard>
    </section>

    <BaseCard variant="panel" class="filter-panel">
      <div class="filter-heading"><div><h2>Bộ lọc lịch sử</h2><p>Điều kiện chỉ được áp dụng khi bạn xác nhận để tránh thay đổi bảng trong lúc nhập.</p></div><div class="filter-tags"><StatusBadge status="info" :label="`${total} bản ghi`"/><StatusBadge v-for="tag in appliedFilterTags" :key="tag" status="neutral" :label="tag"/></div></div>
      <div class="filter-grid">
        <BaseField for-id="access-query" label="Từ khóa" v-slot="field"><BaseInput id="access-query" v-model="draftFilters.query" type="search" placeholder="Tên, biển số hoặc ghi chú" :describedby="field.describedby" @keyup.enter="applyFilters"/></BaseField>
        <BaseField for-id="access-direction" label="Chiều di chuyển" v-slot="field"><BaseSelect id="access-direction" v-model="draftFilters.direction" :describedby="field.describedby"><option value="">Tất cả chiều</option><option value="IN">Vào</option><option value="OUT">Ra</option></BaseSelect></BaseField>
        <BaseField for-id="access-gate" label="Cổng" v-slot="field"><BaseSelect id="access-gate" v-model="draftFilters.gateId" :describedby="field.describedby"><option value="">Tất cả cổng</option><option v-for="gate in gates" :key="gate.gateId" :value="String(gate.gateId)">{{ gate.gateName }}</option></BaseSelect></BaseField>
        <BaseField for-id="access-status" label="Trạng thái" v-slot="field"><BaseSelect id="access-status" v-model="draftFilters.status" :describedby="field.describedby"><option value="">Tất cả trạng thái</option><option v-for="status in statusOptions" :key="status" :value="status">{{ status }}</option></BaseSelect></BaseField>
        <BaseField for-id="access-date-from" label="Từ ngày" v-slot="field"><BaseInput id="access-date-from" v-model="draftFilters.dateFrom" type="date" :describedby="field.describedby"/></BaseField>
        <BaseField for-id="access-date-to" label="Đến ngày" v-slot="field"><BaseInput id="access-date-to" v-model="draftFilters.dateTo" type="date" :describedby="field.describedby"/></BaseField>
      </div>
      <footer class="filter-footer"><p :class="{'is-notice':filterNotice}" aria-live="polite">{{ filterNotice || 'Khoảng ngày nhập ngược sẽ được tự động chuẩn hóa.' }}</p><div><BaseButton variant="ghost" :disabled="isLoading&&!hasPendingChanges" @click="resetFilters">Đặt lại</BaseButton><BaseButton :disabled="!hasPendingChanges&&!filterNotice" @click="applyFilters">Áp dụng lọc</BaseButton></div></footer>
    </BaseCard>

    <section class="list-panel" aria-labelledby="access-list-title"><div class="list-title"><h2 id="access-list-title">Bản ghi truy cập</h2><p>Ảnh bằng chứng được tải trì hoãn để giảm thời gian hiển thị ban đầu.</p></div>
      <DataTable :columns="columns" :rows="items" row-key="logId" :loading="isLoading" :error="loadError" :permission-denied="permissionDenied" empty-title="Không có bản ghi phù hợp" :empty-description="hasActiveFilters?'Thử nới lỏng điều kiện hoặc đặt lại bộ lọc.':'Sự kiện mới sẽ xuất hiện tại đây.'">
        <template #retry><BaseButton variant="secondary" @click="fetchLogs">Thử lại</BaseButton></template><template #empty-actions><BaseButton v-if="hasActiveFilters" variant="secondary" @click="resetFilters">Đặt lại bộ lọc</BaseButton></template>
        <template #cell-timestamp="{value}"><time :datetime="value">{{ formatDateTime(value) }}</time></template>
        <template #cell-actor="{row}"><div class="stacked-cell"><strong>{{ row.actorName||'Chưa xác định' }}</strong><small>{{ actorTypeLabel(row.actorType) }}</small></div></template>
        <template #cell-direction="{value}"><StatusBadge :status="value==='IN'?'success':'info'" :label="value==='IN'?'Vào':'Ra'" dot/></template>
        <template #cell-gate="{row}"><div class="stacked-cell"><strong>{{ row.gateName||'Chưa gán cổng' }}</strong><small>{{ row.cameraName||'Không có camera' }}</small></div></template>
        <template #cell-capturedLicensePlate="{value}"><span v-if="value" class="license-plate">{{ value }}</span><span v-else class="muted">Không ghi nhận</span></template>
        <template #cell-method="{value}"><StatusBadge :status="methodSemantic(value)" :label="methodLabel(value)"/></template>
        <template #cell-evidence="{row}"><div v-if="evidenceUrls(row).length" class="evidence-thumbs"><BaseButton v-for="(item,index) in evidenceUrls(row).slice(0,3)" :key="item.url" variant="secondary" size="small" class="evidence-thumb" :aria-label="`Xem ${item.label}`" @click="openEvidence(row,index)"><img :src="item.url" :alt="item.label" loading="lazy" @error="$event.currentTarget.parentElement.hidden=true"/></BaseButton><span v-if="evidenceUrls(row).length>3" class="muted">+{{ evidenceUrls(row).length-3 }}</span></div><span v-else class="muted">Không có</span></template>
        <template #cell-resultStatus="{row}"><div class="status-stack"><StatusBadge v-if="row.resultStatus" :status="resultSemantic(row.resultStatus)" :label="row.resultStatus" dot/><StatusBadge v-if="row.isBypass" status="danger" label="BYPASS"/><StatusBadge v-if="row.isException" status="warning" label="NGOẠI LỆ"/></div></template>
        <template #actions="{row}"><BaseButton variant="ghost" size="small" @click="openDetail(row.logId)">Chi tiết</BaseButton></template>
      </DataTable>
      <footer v-if="!isLoading&&!loadError&&total" class="pagination-bar"><span>Hiển thị {{ items.length }} trong {{ total }} bản ghi</span><div class="pagination-actions"><BaseButton variant="secondary" size="small" :disabled="page<=1" @click="setPage(page-1)">Trang trước</BaseButton><span>Trang {{ page }} / {{ totalPages }}</span><BaseButton variant="secondary" size="small" :disabled="page>=totalPages" @click="setPage(page+1)">Trang sau</BaseButton></div></footer>
    </section>

    <BaseModal :open="showDetailModal" :title="`Chi tiết bản ghi #${detail?.logId||detailId||''}`" description="Ngữ cảnh nhận diện, kết quả và bằng chứng liên quan." @close="closeDetail">
      <LoadingSkeleton v-if="detailLoading" variant="card" :lines="5"/><EmptyState v-else-if="detailError" kind="error" title="Không thể tải chi tiết" :description="detailError"><template #actions><BaseButton variant="secondary" @click="openDetail(detailId)">Thử lại</BaseButton></template></EmptyState>
      <div v-else-if="detail" class="detail-content"><dl class="detail-grid"><div><dt>Thời gian</dt><dd>{{ formatDateTime(detail.timestamp) }}</dd></div><div><dt>Kết quả</dt><dd><StatusBadge :status="resultSemantic(detail.resultStatus)" :label="detail.resultStatus||'Không xác định'"/></dd></div><div><dt>Đối tượng</dt><dd>{{ detail.actorName||'—' }}</dd></div><div><dt>Loại đối tượng</dt><dd>{{ actorTypeLabel(detail.actorType) }}</dd></div><div><dt>Cổng</dt><dd>{{ detail.gateName||'—' }}</dd></div><div><dt>Camera</dt><dd>{{ detail.cameraName||'—' }}</dd></div><div><dt>Phương thức</dt><dd>{{ methodLabel(detail.method) }}</dd></div><div><dt>Biển số</dt><dd>{{ detail.capturedLicensePlate||'—' }}</dd></div><div class="wide"><dt>Ghi chú / ngoại lệ</dt><dd>{{ detail.note||detail.exceptionReasonDescription||'Không có' }}</dd></div></dl><section v-if="evidenceUrls(detail).length" class="detail-evidence"><h3>Bằng chứng</h3><div><BaseButton v-for="(item,index) in evidenceUrls(detail)" :key="item.url" variant="secondary" class="evidence-card" @click="openEvidence(detail,index)"><img :src="item.url" :alt="item.label" loading="lazy"/><span>{{ item.label }}</span></BaseButton></div></section></div>
    </BaseModal>

    <BaseModal :open="Boolean(evidencePreview)" :title="evidencePreview?.label||'Bằng chứng'" description="Ảnh bằng chứng gốc của sự kiện truy cập." @close="evidencePreview=null"><figure v-if="evidencePreview" class="evidence-preview"><img :src="evidencePreview.url" :alt="evidencePreview.label"/><figcaption>{{ evidencePreview.position }} · {{ formatDateTime(evidencePreview.timestamp) }}</figcaption></figure><template #footer><BaseButton variant="secondary" @click="evidencePreview=null">Đóng</BaseButton><BaseButton :href="evidencePreview?.url" target="_blank" rel="noopener noreferrer">Mở ảnh gốc</BaseButton></template></BaseModal>
    <ExportModal v-if="showExportModal" entity-type="AccessLog" entity-display-name="Lịch sử ra vào" :available-columns="['LogId','Timestamp','ActorName','ActorType','Direction','GateName','CameraName','CapturedLicensePlate','Method','ResultStatus','Note']" @close="showExportModal=false"/>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getAccessLogDetail, getAccessLogs, getAccessLogSummary } from '../services/accessLogApi'
import { getGates } from '../services/deviceManagementApi'
import BaseButton from '../components/ui/BaseButton.vue';import BaseCard from '../components/ui/BaseCard.vue';import BaseField from '../components/ui/BaseField.vue';import BaseInput from '../components/ui/BaseInput.vue';import BaseModal from '../components/ui/BaseModal.vue';import BaseSelect from '../components/ui/BaseSelect.vue';import DataTable from '../components/ui/DataTable.vue';import EmptyState from '../components/ui/EmptyState.vue';import LoadingSkeleton from '../components/ui/LoadingSkeleton.vue';import PageHeader from '../components/ui/PageHeader.vue';import StatusBadge from '../components/ui/StatusBadge.vue';import ExportModal from '../components/import-export/ExportModal.vue'

const route=useRoute();const router=useRouter();const pageSize=12;const defaults=()=>({query:'',direction:'',gateId:'',status:'',dateFrom:'',dateTo:''})
const isLoading=ref(true);const loadError=ref('');const permissionDenied=ref(false);const items=ref([]);const total=ref(0);const page=ref(1);const gates=ref([]);const filterNotice=ref('');const draftFilters=reactive(defaults());const appliedFilters=ref(defaults());const summary=ref({totalToday:0,entriesToday:0,exitsToday:0,exceptionsToday:0,bypassToday:0,vehiclesInside:0,successRate:0});const showExportModal=ref(false);const showDetailModal=ref(false);const detail=ref(null);const detailId=ref(null);const detailLoading=ref(false);const detailError=ref('');const evidencePreview=ref(null)
const columns=[{key:'timestamp',label:'Thời gian'},{key:'actor',label:'Đối tượng'},{key:'direction',label:'Chiều'},{key:'gate',label:'Cổng / Camera'},{key:'capturedLicensePlate',label:'Biển số'},{key:'method',label:'Phương thức'},{key:'evidence',label:'Bằng chứng'},{key:'resultStatus',label:'Trạng thái'}];const defaultStatuses=['APPROVED','SUCCESS','MATCHED','GRANTED','OK','DENIED','FAILED','REJECTED']
function normalize(source){const normalized={query:source.query?.trim()||'',direction:source.direction||'',gateId:String(source.gateId||''),status:source.status||'',dateFrom:source.dateFrom||'',dateTo:source.dateTo||''};let swapped=false;if(normalized.dateFrom&&normalized.dateTo&&normalized.dateFrom>normalized.dateTo){[normalized.dateFrom,normalized.dateTo]=[normalized.dateTo,normalized.dateFrom];swapped=true}return{normalized,swapped}}const serialize=source=>JSON.stringify(normalize(source).normalized);const totalPages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize)));const hasPendingChanges=computed(()=>serialize(draftFilters)!==serialize(appliedFilters.value));const hasActiveFilters=computed(()=>Object.values(normalize(appliedFilters.value).normalized).some(Boolean));const statusOptions=computed(()=>[...new Set([...defaultStatuses,...items.value.map(item=>item.resultStatus).filter(Boolean)])]);const appliedFilterTags=computed(()=>{const current=normalize(appliedFilters.value).normalized;const tags=[];if(current.query)tags.push(`Từ khóa: ${current.query}`);if(current.direction)tags.push(`Chiều: ${current.direction==='IN'?'Vào':'Ra'}`);if(current.gateId)tags.push(`Cổng: ${gates.value.find(item=>String(item.gateId)===current.gateId)?.gateName||current.gateId}`);if(current.status)tags.push(`Trạng thái: ${current.status}`);if(current.dateFrom)tags.push(`Từ: ${formatDate(current.dateFrom)}`);if(current.dateTo)tags.push(`Đến: ${formatDate(current.dateTo)}`);return tags})
function applyRoute(){const query=route.query;const next={query:String(query.search||''),direction:['IN','OUT'].includes(String(query.direction))?String(query.direction):'',gateId:String(query.gate||''),status:String(query.status||''),dateFrom:String(query.from||''),dateTo:String(query.to||'')};Object.assign(draftFilters,next);appliedFilters.value={...next};page.value=Math.max(1,Number(query.page)||1)}function queryFor(filters,nextPage=1){return{search:filters.query||undefined,direction:filters.direction||undefined,gate:filters.gateId||undefined,status:filters.status||undefined,from:filters.dateFrom||undefined,to:filters.dateTo||undefined,page:nextPage>1?nextPage:undefined}}
function applyFilters(){const{normalized,swapped}=normalize(draftFilters);Object.assign(draftFilters,normalized);filterNotice.value=swapped?'Khoảng ngày đã được đổi lại đúng thứ tự.':'';router.replace({query:queryFor(normalized,1)})}function resetFilters(){Object.assign(draftFilters,defaults());filterNotice.value='';router.replace({query:{}})}function setPage(next){if(next<1||next>totalPages.value)return;router.replace({query:queryFor(appliedFilters.value,next)})}
async function fetchSummary(){try{summary.value={...summary.value,...(await getAccessLogSummary()).data}}catch{}}async function fetchGates(){try{gates.value=(await getGates()).data||[]}catch{gates.value=[]}}
async function fetchLogs(){isLoading.value=true;loadError.value='';permissionDenied.value=false;try{const current=normalize(appliedFilters.value).normalized;const{data}=await getAccessLogs({page:page.value,pageSize,query:current.query||undefined,direction:current.direction||undefined,gateId:current.gateId||undefined,resultStatus:current.status||undefined,dateFrom:current.dateFrom||undefined,dateTo:current.dateTo||undefined});items.value=data.items||[];total.value=data.total||0;if(page.value>totalPages.value)setPage(totalPages.value)}catch(error){items.value=[];total.value=0;if(error.response?.status===403)permissionDenied.value=true;else loadError.value=error.response?.data?.message||'Không thể tải lịch sử ra vào.'}finally{isLoading.value=false}}async function refreshPage(){await Promise.all([fetchSummary(),fetchLogs()])}
async function openDetail(id){detailId.value=id;showDetailModal.value=true;detailLoading.value=true;detailError.value='';detail.value=null;try{detail.value=(await getAccessLogDetail(id)).data}catch(error){detailError.value=error.response?.status===403?'Bạn không có quyền xem bản ghi này.':error.response?.data?.message||'Không thể tải chi tiết bản ghi.'}finally{detailLoading.value=false}}function closeDetail(){showDetailModal.value=false;detail.value=null;detailError.value=''}
function evidenceUrls(row){return[{url:row?.capturedSnapshotUrl,label:'Snapshot camera'},{url:row?.capturedPlateCropUrl,label:'Ảnh biển số'},{url:row?.capturedFaceCropUrl,label:'Ảnh khuôn mặt'},{url:row?.capturedQrSnapshotUrl,label:'Snapshot QR'}].filter(item=>item.url)}function openEvidence(row,index){const item=evidenceUrls(row)[index];if(item)evidencePreview.value={...item,position:row.gateName||row.cameraName||'Không rõ vị trí',timestamp:row.timestamp}}
function formatDate(value){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleDateString('vi-VN')}function formatDateTime(value){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit',year:'numeric'})}function actorTypeLabel(value){return{Employee:'Nhân sự nội bộ',Guest:'Khách / đăng ký trước',Unknown:'Chưa xác định'}[value]||'Chưa phân loại'}function methodLabel(value){return{face:'Khuôn mặt',plate:'Biển số',manual:'Thủ công',qr:'QR Code','face-and-plate':'Khuôn mặt + biển số',system:'Hệ thống'}[value]||value||'Không rõ'}function methodSemantic(value){return value==='manual'?'danger':value==='plate'?'warning':['face','qr','face-and-plate'].includes(value)?'success':'neutral'}function resultSemantic(value){const status=String(value||'').toUpperCase();return['DENIED','FAILED','REJECTED'].includes(status)?'danger':['APPROVED','SUCCESS','MATCHED','GRANTED','OK'].includes(status)?'success':'neutral'}
onMounted(async()=>{applyRoute();await Promise.all([fetchSummary(),fetchGates(),fetchLogs()])});watch(()=>route.query,async()=>{applyRoute();await fetchLogs()},{deep:true})
</script>

<style scoped>
.access-page{display:grid;gap:var(--space-6)}.summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--space-4)}.summary-grid span,.summary-grid small{display:block;color:var(--text-secondary);font-size:var(--type-caption-size);line-height:var(--type-caption-line)}.summary-grid strong{display:block;margin-block:var(--space-2);font-size:var(--type-h2-size);line-height:var(--type-h2-line)}
.filter-panel{display:grid;gap:var(--space-5)}.filter-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--space-4)}.filter-heading h2,.list-title h2{font-size:var(--type-h2-size);line-height:var(--type-h2-line)}.filter-heading p,.list-title p{color:var(--text-secondary);font-size:var(--type-body-size)}.filter-tags{display:flex;justify-content:flex-end;flex-wrap:wrap;gap:var(--space-2)}.filter-grid{display:grid;grid-template-columns:2fr repeat(3,1fr) 1fr 1fr;gap:var(--space-3)}.filter-footer{display:flex;align-items:center;justify-content:space-between;gap:var(--space-4);padding-top:var(--space-4);border-top:1px solid var(--border-subtle)}.filter-footer p{color:var(--text-muted);font-size:var(--type-caption-size)}.filter-footer p.is-notice{color:var(--status-info-text)}.filter-footer>div{display:flex;gap:var(--space-2)}
.list-panel{display:grid;gap:var(--space-4)}.stacked-cell{display:grid;gap:var(--space-1)}.stacked-cell small,.muted{color:var(--text-muted);font-size:var(--type-caption-size)}.license-plate{display:inline-flex;padding:var(--space-1) var(--space-2);border:1px solid var(--border-strong);border-radius:var(--radius-control);background:var(--surface-subtle);font-weight:800;letter-spacing:.05em}.status-stack{display:flex;align-items:center;flex-wrap:wrap;gap:var(--space-1)}.evidence-thumbs{display:flex;align-items:center;gap:var(--space-1)}.evidence-thumb{width:36px;height:36px;padding:0;border:1px solid var(--border-default);border-radius:var(--radius-control);overflow:hidden}.evidence-thumb:focus-visible{outline:3px solid var(--border-focus);outline-offset:2px}.evidence-thumb img{width:100%;height:100%;object-fit:cover}.pagination-bar,.pagination-actions{display:flex;align-items:center;gap:var(--space-3)}.pagination-bar{justify-content:space-between;color:var(--text-secondary);font-size:var(--type-body-size)}
.detail-content{display:grid;gap:var(--space-5)}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-3);margin:0}.detail-grid div{display:grid;gap:var(--space-1);padding:var(--space-3);border:1px solid var(--border-subtle);border-radius:var(--radius-control);background:var(--surface-subtle)}.detail-grid .wide{grid-column:1/-1}.detail-grid dt{color:var(--text-muted);font-size:var(--type-caption-size)}.detail-grid dd{margin:0;font-weight:700}.detail-evidence{display:grid;gap:var(--space-3)}.detail-evidence h3{font-size:var(--type-h3-size)}.detail-evidence>div{display:grid;grid-template-columns:repeat(2,1fr);gap:var(--space-3)}.detail-evidence .evidence-card{min-height:auto;height:auto;display:grid;gap:var(--space-2);padding:var(--space-2);text-align:left}.detail-evidence img{width:100%;height:140px;border-radius:var(--radius-control);object-fit:cover}.evidence-preview{display:grid;gap:var(--space-3);margin:0}.evidence-preview img{width:100%;max-height:60vh;border-radius:var(--radius-card);object-fit:contain;background:var(--surface-subtle)}.evidence-preview figcaption{color:var(--text-secondary);font-size:var(--type-body-size)}
@media(max-width:1200px){.summary-grid{grid-template-columns:repeat(2,1fr)}.filter-grid{grid-template-columns:repeat(3,1fr)}.filter-grid>:first-child{grid-column:span 2}}@media(max-width:768px){.summary-grid,.filter-grid,.detail-grid,.detail-evidence>div{grid-template-columns:1fr}.filter-grid>:first-child,.detail-grid .wide{grid-column:auto}.filter-heading,.filter-footer,.pagination-bar{align-items:flex-start;display:grid}.filter-tags{justify-content:flex-start}.filter-footer>div,.pagination-actions{flex-wrap:wrap}}
</style>
