<template>
  <div class="page-container vehicles-page">
    <PageHeader title="Quản lý phương tiện" description="Đăng ký phương tiện, chủ sở hữu và phân loại biển số phục vụ kiểm soát ra vào." :breadcrumbs="[{ label: 'Phương tiện' }, { label: 'Danh sách' }]">
      <template #actions><BaseButton variant="secondary" @click="showImportModal=true">Nhập dữ liệu</BaseButton><BaseButton variant="secondary" @click="showExportModal=true">Xuất dữ liệu</BaseButton><BaseButton @click="openModal()">Đăng ký phương tiện</BaseButton></template>
    </PageHeader>

    <section class="summary-grid" aria-label="Tổng quan phương tiện">
      <BaseCard variant="kpi"><span>Tổng phương tiện</span><strong>{{ vehicles.length }}</strong><small>Đã đăng ký trong hệ thống</small></BaseCard>
      <BaseCard variant="kpi"><span>Chủ sở hữu</span><strong>{{ uniqueOwnerCount }}</strong><small>Nhân viên có phương tiện</small></BaseCard>
      <BaseCard variant="kpi"><span>Loại xe</span><strong>{{ vehicleTypes.length }}</strong><small>Danh mục đang sử dụng</small></BaseCard>
    </section>

    <section class="list-panel" aria-labelledby="vehicle-list-title">
      <div class="list-toolbar"><div><h2 id="vehicle-list-title">Danh sách phương tiện</h2><p>{{ filteredVehicles.length }} kết quả phù hợp</p></div><div class="filter-bar" role="search"><BaseInput id="vehicle-search" v-model="searchQuery" type="search" aria-label="Tìm phương tiện" placeholder="Biển số, chủ xe hoặc mô tả" @input="debouncedCommitFilters"/><BaseSelect id="vehicle-type-filter" v-model="filterType" aria-label="Lọc loại xe" @update:model-value="commitFilters"><option value="">Tất cả loại xe</option><option v-for="type in vehicleTypes" :key="type" :value="type">{{ type }}</option></BaseSelect><BaseButton v-if="hasActiveFilters" variant="ghost" @click="clearFilters">Xóa lọc</BaseButton><BaseButton variant="secondary" :loading="loading" @click="fetchVehicles">Làm mới</BaseButton></div></div>

      <DataTable :columns="columns" :rows="paginatedVehicles" row-key="vehicleId" :loading="loading" :error="loadError" :permission-denied="permissionDenied" empty-title="Không có phương tiện phù hợp" empty-description="Thử thay đổi bộ lọc hoặc đăng ký phương tiện mới.">
        <template #retry><BaseButton variant="secondary" @click="fetchVehicles">Thử lại</BaseButton></template><template #empty-actions><BaseButton @click="openModal()">Đăng ký phương tiện</BaseButton></template>
        <template #cell-licensePlate="{ value }"><span class="license-plate">{{ value }}</span></template>
        <template #cell-vehicleTypeName="{ value }"><StatusBadge status="info" :label="value || 'Chưa phân loại'" /></template>
        <template #cell-owner="{ row }"><div class="identity-cell"><img v-if="getEmployeeFaceSrc(row.employeeId)" :src="getEmployeeFaceSrc(row.employeeId)" class="avatar" alt="" @error="markAvatarBroken(row.employeeId,$event)"/><span v-else class="avatar avatar-fallback" :class="`tone-${Number(row.employeeId||0)%5}`">{{ getInitials(row.employeeFullName) }}</span><span><strong>{{ row.employeeFullName || 'Chưa gán chủ sở hữu' }}</strong><small>ID {{ row.employeeId || '—' }}</small></span></div></template>
        <template #cell-description="{ value }"><span class="description-cell">{{ value || 'Không có mô tả' }}</span></template>
        <template #actions="{ row }"><div class="row-actions"><BaseButton variant="ghost" size="small" @click="openModal(row)">Sửa</BaseButton><BaseButton variant="ghost" size="small" @click="requestDelete(row)">Xóa</BaseButton></div></template>
      </DataTable>

      <footer v-if="!loading&&!loadError&&filteredVehicles.length" class="pagination-bar"><span>Hiển thị {{ pagStart }}–{{ pagEnd }} trong {{ filteredVehicles.length }}</span><div class="pagination-actions"><BaseButton variant="secondary" size="small" :disabled="currentPage<=1" @click="setPage(currentPage-1)">Trang trước</BaseButton><span>Trang {{ currentPage }} / {{ totalPages }}</span><BaseButton variant="secondary" size="small" :disabled="currentPage>=totalPages" @click="setPage(currentPage+1)">Trang sau</BaseButton></div></footer>
    </section>

    <BaseModal :open="showModal" :title="editingVehicle?'Cập nhật phương tiện':'Đăng ký phương tiện'" description="Biển số được chuẩn hóa và đối chiếu loại xe trước khi lưu." @close="requestCloseModal">
      <form id="vehicle-form" class="vehicle-form" @submit.prevent="saveVehicle">
        <div class="form-grid">
          <BaseField for-id="vehicle-plate" label="Biển số xe" required :error="plateError" :success="plateSuccess" v-slot="field"><BaseInput id="vehicle-plate" v-model="form.licensePlate" :describedby="field.describedby" :invalid="field.invalid" autocomplete="off" placeholder="Ví dụ: 51A-123.45" @input="onPlateInput" @blur="plateValidation.touched=true;onPlateInput()"/></BaseField>
          <BaseField v-if="editingVehicle" for-id="vehicle-type" label="Loại xe" description="Chỉ điều chỉnh thủ công khi cập nhật." v-slot="field"><BaseSelect id="vehicle-type" v-model="form.vehicleTypeId" :describedby="field.describedby"><option value="">Chọn loại xe</option><option v-for="type in vehicleTypeOptions" :key="type.vehicleTypeId" :value="type.vehicleTypeId">{{ type.typeName }}</option></BaseSelect></BaseField>
          <BaseField v-else for-id="vehicle-inferred-type" label="Loại xe tự nhận diện" description="Được suy luận từ định dạng biển số." v-slot="field"><BaseInput id="vehicle-inferred-type" :model-value="inferredVehicleTypeLabel" readonly :describedby="field.describedby"/></BaseField>
        </div>
        <BaseField for-id="vehicle-owner" label="Chủ sở hữu" required description="Nhập tên để tìm, sau đó chọn đúng gợi ý." :error="ownerError" v-slot="field"><BaseInput id="vehicle-owner" v-model="ownerSearchQuery" list="vehicle-owner-options" autocomplete="off" :describedby="field.describedby" :invalid="field.invalid" placeholder="Tên hoặc ID nhân viên" @input="resolveOwner"/><datalist id="vehicle-owner-options"><option v-for="employee in filteredOwnerEmployees" :key="employee.employeeId" :value="ownerOption(employee)">{{ employee.departmentName || 'Chưa có phòng ban' }}</option></datalist></BaseField>
        <BaseField for-id="vehicle-description" label="Mô tả" :counter="`${form.description.length}/200`" v-slot="field"><BaseTextarea id="vehicle-description" v-model="form.description" maxlength="200" rows="3" :describedby="field.describedby" placeholder="Màu xe hoặc thông tin nhận diện khác"/></BaseField>
        <p v-if="modalError" class="form-error" role="alert">{{ modalError }}</p>
      </form>
      <template #footer><BaseButton variant="secondary" :disabled="saving" @click="requestCloseModal">Hủy</BaseButton><BaseButton type="submit" form="vehicle-form" :loading="saving">{{ editingVehicle?'Lưu thay đổi':'Đăng ký' }}</BaseButton></template>
    </BaseModal>

    <ConfirmDialog :open="Boolean(deleteTarget)" kind="destructive" title="Xóa phương tiện?" :description="`Biển số ${deleteTarget?.licensePlate||''} sẽ bị gỡ khỏi hệ thống. Hành động này không thể hoàn tác.`" confirm-label="Xóa phương tiện" :loading="saving" @cancel="deleteTarget=null" @confirm="executeDelete"/>
    <ConfirmDialog :open="showDiscardDialog" title="Bỏ thay đổi chưa lưu?" description="Thông tin phương tiện bạn vừa nhập sẽ bị mất." confirm-label="Bỏ thay đổi" @cancel="showDiscardDialog=false" @confirm="closeModal(true)"/>
    <ImportModal v-if="showImportModal" entity-type="Vehicle" entity-display-name="Phương tiện" @close="showImportModal=false" @import-complete="onImportComplete"/>
    <ExportModal v-if="showExportModal" entity-type="Vehicle" entity-display-name="Phương tiện" :available-columns="['VehicleId','LicensePlate','VehicleTypeName','EmployeeCode','Description']" @close="showExportModal=false"/>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import * as vehicleApi from '../services/vehicleApi'
import { getAll as getAllEmployees, getProtectedFaceImage } from '../services/employeeApi'
import { getVehicleTypeLabel, optimizeAndValidatePlate } from '../utils/licensePlateValidator'
import BaseButton from '../components/ui/BaseButton.vue'
import BaseCard from '../components/ui/BaseCard.vue'
import BaseField from '../components/ui/BaseField.vue'
import BaseInput from '../components/ui/BaseInput.vue'
import BaseModal from '../components/ui/BaseModal.vue'
import BaseSelect from '../components/ui/BaseSelect.vue'
import BaseTextarea from '../components/ui/BaseTextarea.vue'
import ConfirmDialog from '../components/ui/ConfirmDialog.vue'
import DataTable from '../components/ui/DataTable.vue'
import PageHeader from '../components/ui/PageHeader.vue'
import StatusBadge from '../components/ui/StatusBadge.vue'
import ImportModal from '../components/import-export/ImportModal.vue'
import ExportModal from '../components/import-export/ExportModal.vue'
import { useToasts } from '../composables/useToasts'

const route=useRoute();const router=useRouter();const{success,error:showError}=useToasts()
const vehicles=ref([]);const employeeList=ref([]);const vehicleTypeOptions=ref([]);const loading=ref(true);const loadError=ref('');const permissionDenied=ref(false);const searchQuery=ref('');const filterType=ref('');const currentPage=ref(1);const pageSize=10;let filterTimer=null
const showImportModal=ref(false);const showExportModal=ref(false);const showModal=ref(false);const showDiscardDialog=ref(false);const editingVehicle=ref(null);const saving=ref(false);const modalError=ref('');const deleteTarget=ref(null);const ownerSearchQuery=ref('');const form=reactive({licensePlate:'',vehicleTypeId:'',employeeId:null,description:''});const formBaseline=ref('');const formSubmitted=ref(false)
const protectedAvatarUrls=ref({});const brokenAvatarIds=ref({});const plateValidation=reactive({touched:false,isValid:false,type:'Unknown',typeLabel:'',cleanedPlate:'',corrected:false})
const columns=[{key:'licensePlate',label:'Biển số'},{key:'vehicleTypeName',label:'Loại xe'},{key:'owner',label:'Chủ sở hữu'},{key:'description',label:'Mô tả'}]
const uniqueOwnerCount=computed(()=>new Set(vehicles.value.filter(item=>item.employeeId).map(item=>item.employeeId)).size);const vehicleTypes=computed(()=>[...new Set(vehicles.value.map(item=>item.vehicleTypeName).filter(Boolean))]);const hasActiveFilters=computed(()=>Boolean(searchQuery.value||filterType.value));const filteredVehicles=computed(()=>vehicles.value.filter(item=>{const query=searchQuery.value.trim().toLocaleLowerCase('vi');const matchSearch=!query||[item.licensePlate,item.employeeFullName,item.description].some(value=>String(value||'').toLocaleLowerCase('vi').includes(query));return matchSearch&&(!filterType.value||item.vehicleTypeName===filterType.value)}));const totalPages=computed(()=>Math.max(1,Math.ceil(filteredVehicles.value.length/pageSize)));const paginatedVehicles=computed(()=>filteredVehicles.value.slice((currentPage.value-1)*pageSize,currentPage.value*pageSize));const pagStart=computed(()=>filteredVehicles.value.length?(currentPage.value-1)*pageSize+1:0);const pagEnd=computed(()=>Math.min(currentPage.value*pageSize,filteredVehicles.value.length))
const normalizeType=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();function resolveVehicleTypeIdByPlateType(type){const aliases=type==='Car'?['o to','xe hoi','car']:type==='Motorcycle'?['xe may','motorcycle','motorbike','moto']:[];return vehicleTypeOptions.value.find(item=>aliases.some(alias=>normalizeType(item.typeName).includes(alias)))?.vehicleTypeId||null}const inferredVehicleTypeId=computed(()=>plateValidation.isValid?resolveVehicleTypeIdByPlateType(plateValidation.type):null);const inferredVehicleTypeLabel=computed(()=>!plateValidation.touched?'Sẽ tự nhận diện sau khi nhập biển số':plateValidation.isValid&&inferredVehicleTypeId.value?getVehicleTypeLabel(plateValidation.type):'Chưa xác định được loại xe')
const plateError=computed(()=>plateValidation.touched&&!plateValidation.isValid?'Biển số không đúng định dạng Việt Nam. Ví dụ: 51A-123.45.':formSubmitted.value&&!form.licensePlate.trim()?'Biển số là bắt buộc.':'');const plateSuccess=computed(()=>plateValidation.isValid?`Hợp lệ · ${plateValidation.typeLabel}${plateValidation.corrected?` · Chuẩn hóa thành ${plateValidation.cleanedPlate}`:''}`:'');const ownerError=computed(()=>formSubmitted.value&&!form.employeeId?'Chọn một nhân viên từ danh sách gợi ý.':'');const formState=computed(()=>JSON.stringify(form));const formDirty=computed(()=>showModal.value&&formState.value!==formBaseline.value)
const ownerOption=employee=>`${employee.fullName} · ID ${employee.employeeId}`;const filteredOwnerEmployees=computed(()=>{const query=ownerSearchQuery.value.toLocaleLowerCase('vi');if(!query)return employeeList.value;return employeeList.value.filter(item=>ownerOption(item).toLocaleLowerCase('vi').includes(query)||String(item.departmentName||'').toLocaleLowerCase('vi').includes(query))})
function applyQuery(){searchQuery.value=String(route.query.search||'');filterType.value=String(route.query.type||'');currentPage.value=Math.max(1,Number(route.query.page)||1)}function commitFilters(){router.replace({query:{...route.query,search:searchQuery.value.trim()||undefined,type:filterType.value||undefined,page:undefined}})}function debouncedCommitFilters(){clearTimeout(filterTimer);filterTimer=setTimeout(commitFilters,350)}function clearFilters(){searchQuery.value='';filterType.value='';commitFilters()}function setPage(page){router.replace({query:{...route.query,page:page>1?page:undefined}})}
async function fetchVehicles(){loading.value=true;loadError.value='';permissionDenied.value=false;try{vehicles.value=(await vehicleApi.getAll()).data||[];if(currentPage.value>totalPages.value)setPage(totalPages.value)}catch(err){vehicles.value=[];if(err.response?.status===403)permissionDenied.value=true;else loadError.value=err.response?.data?.message||'Không thể tải danh sách phương tiện.'}finally{loading.value=false}}
async function fetchReferences(){try{const[types,employees]=await Promise.all([vehicleApi.getTypes(),getAllEmployees()]);vehicleTypeOptions.value=Array.isArray(types.data)?types.data:[];employeeList.value=employees.data||[];await hydrateProtectedAvatars(employeeList.value)}catch{showError('Một số danh mục chưa tải được','Thử làm mới trang trước khi đăng ký phương tiện.')}}
function resetPlateValidation(){Object.assign(plateValidation,{touched:false,isValid:false,type:'Unknown',typeLabel:'',cleanedPlate:'',corrected:false})}function onPlateInput(){const value=form.licensePlate.trim();if(!value){plateValidation.isValid=false;plateValidation.cleanedPlate='';return}plateValidation.touched=true;const result=optimizeAndValidatePlate(value);Object.assign(plateValidation,{isValid:result.isValid,type:result.type,typeLabel:getVehicleTypeLabel(result.type),cleanedPlate:result.cleanedPlate,corrected:result.cleanedPlate!==result.rawInput});if(!editingVehicle.value)form.vehicleTypeId=result.isValid?resolveVehicleTypeIdByPlateType(result.type)||'':''}
function openModal(vehicle=null){editingVehicle.value=vehicle;modalError.value='';formSubmitted.value=false;resetPlateValidation();Object.assign(form,{licensePlate:vehicle?.licensePlate||'',vehicleTypeId:vehicle?.vehicleTypeId||'',employeeId:vehicle?.employeeId||null,description:vehicle?.description||''});ownerSearchQuery.value=vehicle?ownerOption({fullName:vehicle.employeeFullName||'Không rõ',employeeId:vehicle.employeeId}):'';if(vehicle?.licensePlate)onPlateInput();showModal.value=true;queueMicrotask(()=>{formBaseline.value=formState.value})}function requestCloseModal(){if(formDirty.value){showDiscardDialog.value=true;return}closeModal(true)}function closeModal(force=false){if(!force&&formDirty.value)return requestCloseModal();showModal.value=false;showDiscardDialog.value=false;editingVehicle.value=null;modalError.value='';ownerSearchQuery.value=''}
function resolveOwner(){const normalized=ownerSearchQuery.value.trim().toLocaleLowerCase('vi');const match=employeeList.value.find(item=>ownerOption(item).toLocaleLowerCase('vi')===normalized);form.employeeId=match?.employeeId||null}
async function saveVehicle(){formSubmitted.value=true;plateValidation.touched=true;onPlateInput();if(!plateValidation.isValid||!form.employeeId)return;const inferredId=resolveVehicleTypeIdByPlateType(plateValidation.type);if(!editingVehicle.value&&!inferredId){modalError.value='Không thể đối chiếu loại xe với danh mục hệ thống.';return}saving.value=true;modalError.value='';const isEditing=Boolean(editingVehicle.value);try{const payload={licensePlate:plateValidation.cleanedPlate||form.licensePlate.trim(),vehicleTypeId:isEditing?Number(form.vehicleTypeId)||null:inferredId,employeeId:form.employeeId,description:form.description||null};if(isEditing)await vehicleApi.update(editingVehicle.value.vehicleId,payload);else await vehicleApi.create(payload);closeModal(true);success(isEditing?'Đã cập nhật phương tiện':'Đã đăng ký phương tiện');await fetchVehicles()}catch(err){modalError.value=err.response?.data?.message||err.response?.data?.title||'Không thể lưu phương tiện. Dữ liệu nhập vẫn được giữ lại.'}finally{saving.value=false}}
function requestDelete(vehicle){deleteTarget.value=vehicle}async function executeDelete(){if(!deleteTarget.value)return;saving.value=true;try{await vehicleApi.deleteVehicle(deleteTarget.value.vehicleId);deleteTarget.value=null;success('Đã xóa phương tiện');await fetchVehicles()}catch(err){showError('Không thể xóa phương tiện',err.response?.data?.message||'Máy chủ không xử lý được yêu cầu.')}finally{saving.value=false}}function onImportComplete(result){showImportModal.value=false;fetchVehicles();const message=`${result.successCount} bản ghi thành công${result.errorCount?`, ${result.errorCount} lỗi`:''}`;result.errorCount?showError('Import hoàn tất có lỗi',message):success('Import hoàn tất',message)}
function getInitials(name){return String(name||'?').split(/\s+/).filter(Boolean).slice(-2).map(word=>word[0]).join('').toUpperCase()}function getEmployeeFaceSrc(id){if(brokenAvatarIds.value[id])return'';const employee=employeeList.value.find(item=>item.employeeId===id);if(!employee?.faceImageUrl)return'';return /^https?:\/\//.test(employee.faceImageUrl)?employee.faceImageUrl:protectedAvatarUrls.value[id]||''}function markAvatarBroken(id,event){if(event?.target)event.target.hidden=true;brokenAvatarIds.value={...brokenAvatarIds.value,[id]:true}}async function hydrateProtectedAvatars(list){releaseProtectedAvatars();const entries=await Promise.all((list||[]).map(async employee=>{if(!employee?.employeeId||!employee.faceImageUrl||/^https?:\/\//.test(employee.faceImageUrl))return[employee?.employeeId,''];try{return[employee.employeeId,URL.createObjectURL((await getProtectedFaceImage(employee.employeeId)).data)]}catch{return[employee.employeeId,'']}}));protectedAvatarUrls.value=Object.fromEntries(entries.filter(([id])=>id))}function releaseProtectedAvatars(){Object.values(protectedAvatarUrls.value).forEach(url=>url&&URL.revokeObjectURL(url));protectedAvatarUrls.value={}}
function beforeUnload(event){if(!formDirty.value)return;event.preventDefault();event.returnValue=''}onMounted(async()=>{applyQuery();window.addEventListener('beforeunload',beforeUnload);await Promise.all([fetchVehicles(),fetchReferences()])});onBeforeUnmount(()=>{clearTimeout(filterTimer);window.removeEventListener('beforeunload',beforeUnload);releaseProtectedAvatars()});watch(()=>route.query,async()=>{applyQuery();await fetchVehicles()},{deep:true})
</script>

<style scoped>
.vehicles-page{display:grid;gap:var(--space-6)}.summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--space-4)}.summary-grid span,.summary-grid small{display:block;color:var(--text-secondary);font-size:var(--type-caption-size);line-height:var(--type-caption-line)}.summary-grid strong{display:block;margin-block:var(--space-2);font-size:var(--type-h2-size);line-height:var(--type-h2-line)}
.list-panel{display:grid;gap:var(--space-4)}.list-toolbar{display:flex;align-items:flex-end;justify-content:space-between;gap:var(--space-4)}.list-toolbar h2{font-size:var(--type-h2-size);line-height:var(--type-h2-line)}.list-toolbar p{color:var(--text-muted);font-size:var(--type-body-size)}.filter-bar{display:grid;grid-template-columns:minmax(240px,1fr) minmax(170px,220px) auto auto;gap:var(--space-2);width:min(100%,760px)}
.license-plate{display:inline-flex;padding:var(--space-2) var(--space-3);border:2px solid var(--border-strong);border-radius:var(--radius-control);background:var(--surface-subtle);font-weight:800;letter-spacing:.06em}.identity-cell{display:flex;align-items:center;gap:var(--space-3)}.identity-cell>span:last-child{display:grid;gap:var(--space-1)}.identity-cell small{color:var(--text-muted)}.avatar{width:40px;height:40px;flex:0 0 40px;border-radius:var(--radius-pill);object-fit:cover}.avatar-fallback{display:grid;place-items:center;background:var(--interactive-primary);color:var(--text-on-interactive);font-weight:800}.tone-1{background:var(--interactive-secondary)}.tone-2{background:var(--status-success-text)}.tone-3{background:var(--status-warning-text)}.tone-4{background:var(--status-danger-text)}.description-cell{display:block;max-width:36ch;overflow:hidden;text-overflow:ellipsis}.row-actions,.pagination-actions{display:flex;align-items:center;gap:var(--space-2);white-space:nowrap}.pagination-bar{display:flex;align-items:center;justify-content:space-between;gap:var(--space-4);color:var(--text-secondary);font-size:var(--type-body-size)}
.vehicle-form{display:grid;gap:var(--space-5)}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-4)}.form-error{padding:var(--space-3);border:1px solid var(--status-danger-border);border-radius:var(--radius-control);background:var(--status-danger-bg);color:var(--status-danger-text);font-size:var(--type-body-size)}
@media(max-width:1024px){.list-toolbar{align-items:stretch;display:grid}.filter-bar{width:100%}}@media(max-width:768px){.summary-grid,.filter-bar,.form-grid{grid-template-columns:1fr}.pagination-bar{align-items:flex-start;display:grid}.pagination-actions,.row-actions{flex-wrap:wrap}}
</style>
